spring:
  redis:
    host: localhost
    port: 6379
    password: xiaojiebin
    #    sentinel:
    #      master: mymaster
    #      nodes: 127.0.0.1:26379
    #      password: xiaojiebin
#    cluster:
#      nodes:
#        - 127.0.0.1:6379
#        - 127.0.0.1:6380
#        - 127.0.0.1:6381
#        - 127.0.0.1:6389
#        - 127.0.0.1:6390
#        - 127.0.0.1:6391
    lettuce:
      shutdown-timeout: 1000
      pool:
        enabled: true
        max-active: 200
        max-wait: 3000
        max-idle: 8
        min-idle: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  enabled: true


